language: node_js
node_js:
  - "stable"
jobs:
  include:
    - stage: Prepare Dependencies
      script: "npm ci"
    - stage: Run Build
      script: "npm run build"
    - stage: Run Tests
      script: "npm test"
    - stage: Inject Version
      script: "ls -la"